export const ACTION_TYPES = {
  ADD_WEATHER_DATA: "ADD_WEATHER_DATA",
  ADD_USER_LOCATION: "ADD_USER_LOCATION",
  BLOCK_LOCATION: "BLOCK_LOCATION",
  API_UNAUTHORIZED: "API_UNAUTHORIZED",
  ADD_USER_PLACE: "ADD_USER_PLACE",
  ADD_USER_DATA: "ADD_USER_DATA",
  ADD_TO_SAVED_PLACES: "ADD_TO_SAVED_PLACES",
  ADD_DEFAULT_LOCATION: "ADD_DEFAULT_LOCATION"
};
